package com.example.ui.util

object Localization {
    private val faStrings = mapOf(
        "tab_offline" to "موتور تبدیل آفلاین",
        "tab_favorites" to "علاقه‌مندی‌ها",
        "tab_history" to "تاریخچه مبادلات",
        "tab_settings" to "تنظیمات برنامه",
        
        "settings_header" to "تنظیمات برنامه",
        "settings_desc" to "پیکربندی سنجه‌های نمایش، تم‌ها، بومی‌سازی و تنظیمات پیشرفته سیستم.",
        
        "currency_display_title" to "سیستم محاسباتی و نمایشی",
        "currency_display_desc" to "تعیین مدل مبادلات مالی بر اساس تومان یا ریال (۱ تومان = ۱۰ ریال).",
        "toman_label" to "سیستم تومان (پیش‌فرض)",
        "rial_label" to "سیستم ریال (ضریب ۱۰)",
        
        "theme_title" to "تم رابط کاربری",
        "theme_system" to "پیش‌فرض سیستم",
        "theme_light" to "زیبایی‌شناسی روشن",
        "theme_dark" to "حالت تاریک لوکس",
        
        "lang_title" to "انتخاب زبان برنامه / Language Settings",
        "lang_desc" to "زبان رابط کاربری را به فارسی یا انگلیسی تغییر دهید.",
        "lang_fa" to "فارسی (Persian)",
        "lang_en" to "English (انگلیسی)",
        
        "app_name_custom_title" to "تغییر نام نمایشی اپلیکیشن",
        "app_name_custom_desc" to "نام دلخواه خود را برای نمایش در بالای صفحات بنویسید:",
        "app_name_placeholder" to "نام جدید برنامه...",
        
        "app_icon_custom_title" to "تغییر آیکون و نشان تجاری",
        "app_icon_custom_desc" to "نشان تجاری برنامه را تغییر دهید یا تصویر اختصاصی خود را بارگذاری کنید:",
        "app_icon_modern" to "نشان مدرن درخشان (Modern Modern)",
        "app_icon_gold" to "نشان طلایی سلطنتی (Royal Gold)",
        "app_icon_neon" to "نشان نئون دیجیتال (Digital Neon)",
        "app_icon_vintage" to "نشان کلاسیک پایدار (Vintage Classic)",
        "app_icon_custom" to "تصویر گالری دستگاه / بارگذاری شده با موفقیت",
        "app_icon_gallery_btn" to "انتخاب و بارگذاری تصویر از گالری",
        
        "about_title" to "درباره توسعه‌دهنده و بستر فنی",
        "about_name_label" to "نام برنامه:",
        "about_version_label" to "نسخه:",
        "about_engine_label" to "موتور آفلاین:",
        "about_links_header" to "ارتباط با توسعه‌دهنده:",
        "about_telegram" to "کانال تلگرام من (@digit_bazar)",
        "about_website" to "وب‌سایت شخصی من",
        "about_creator" to "سازنده: Mr.Maxii",
        "created_by" to "طراحی و توسعه: Mr.Maxii",
        
        "search_hint" to "جستجوی ارز یا کد مالی...",
        "add_currency" to "افزودن ارز دلخواه جدید",
        "edit_currency" to "ویرایش جزئیات ارز",
        "code_label" to "کد مالی ارز (مانند CAD)",
        "name_label" to "نام کامل ارز (مانند دلار کانادا)",
        "symbol_label" to "نماد ارز (مانند $)",
        "rate_label" to "ارزش مبادلاتی نسبت به ۱ دلار آمریکا",
        "save" to "ذخیره تغییرات",
        "cancel" to "انصراف",
        "error_invalid" to "لطفاً مقادیر معتبری وارد کنید",
        
        "calc_title" to "ماشین حساب هوشمند مجهز",
        "calc_desc" to "محاسبه عبارات ریاضی و انتقال مستقیم نتیجه به فیلد مقدار ورودی مبادله ارز:",
        "calc_hint" to "مثال: 1500 * (1.10 - 0.05) + 350",
        "calc_btn" to "انتقال نتیجه به کادر مبادلات",
        "calc_error" to "عبارت ریاضی نامعتبر است",
        
        // Favorites
        "fav_header" to "ارزهای علاقه‌مندی شما",
        "fav_desc" to "لیست ارزهایی که برای دسترسی سریع سنجاق کرده‌اید. برای مرتب‌سازی دکمه ویرایش را بزنید و بالا/پایین کنید.",
        "fav_reorder_btn" to "مرتب‌سازی اولویت‌ها",
        "fav_reorder_done" to "اتمام مرتب‌سازی",
        
        // History
        "hist_header" to "تاریخچه و دفتر کل مبادلات",
        "hist_desc" to "ثبت لحظه‌ای تمامی مبادلات آفلاین انجام شده در سیستم جهت رجوع مجدد.",
        "hist_clear_btn" to "پاک کردن کامل آرشیو تاریخچه",
        "hist_empty" to "هنوز هیچ تراکنشی در تاریخچه سیستم ثبت نشده است.",
        
        "calculator_short" to "ماشین حساب",
        
        "sort_fav_first" to "ابتدا علاقه‌مندی‌ها",
        "sort_high_val" to "بیشترین ارزش",
        "sort_low_val" to "کمترین ارزش",
        "sort_alpha_az" to "الفبایی (الف-ی)",
        "sort_alpha_za" to "الفبایی (ی-الف)",
        
        "sync_title" to "همگام‌سازی و بازیابی ارزها",
        "sync_desc" to "در صورت حذف یا ناپدید شدن ارزهای پیش‌فرض همچون طلا، نقره، الماس، افغانی، TON و غیره، دکمه زیر را فشار دهید تا لیست ارزها فوراً از نو فشرده و بازیابی شود.",
        "sync_btn" to "بازیابی و همگام‌سازی ارزهای سیستم",
        "sync_success" to "عملیات همگام‌سازی با موفقیت انجام شد! تمامی ارزها هم‌اکنون به دیتابیس اضافه شدند.",
        "sync_confirm_title" to "تأیید همگام‌سازی",
        "sync_confirm_msg" to "آیا از همگام‌سازی و بازیابی ارزهای پیش‌فرض سیستم مطمئن هستید؟",
        "yes" to "بله",
        "no" to "خیر",

        "cat_all" to "همه ارزها 💫",
        "cat_fiat" to "اسکناس و فیات 💵",
        "cat_crypto" to "ارزهای دیجیتال 🪙",
        "cat_commodity" to "طلا و کالاها ⚜️",

        "app_desc_headline" to "موتور تبدیل آنلاین و آفلاین چندارزی با قابلیت‌های پیشرفته",
        "input_placeholder" to "مقدار مورد نظر برای تبدیل...",
        "input_label" to "مبلغ پایه مبادلات",
        "sort_by" to "مرتب‌سازی:",
        "category_label" to "دسته‌بندی:",
        "no_match_text" to "هیچ ارزی مطابق با جستجوی شما یافت نشد",
        "pinned_favorites" to "ارزهای سنجاق شده (محبوب)",
        "done" to "اتمام",
        "edit" to "ویرایش",
        "fiat_header" to "ارزهای سنتی (فیات) 💵",
        "digital_header" to "ارزهای دیجیتال (رمز ارزها) 🪙",
        "commodity_header" to "طلا، کالاها و فلزات گرانبها ⚜️",
        "fiat_arrow" to "فیات 💵 ➔",
        "crypto_arrow" to "دیجیتال 🪙 ➔",
        "gold_arrow" to "طلا/کالا ⚜️ ➔",
        "favorites_empty_title" to "هنوز هیچ ارز علاقه‌مندی ثبت نشده است",
        "favorites_empty_desc" to "به بخش 'موتور تبدیل آفلاین' بروید و روی آیکون ستاره در هر ارز ضربه بزنید تا در اینجا سنجاق شود.",
        "history_empty_title" to "دفتر کل تراکنش‌ها خالی است",
        "history_empty_desc" to "محاسبات آفلاین خود را در موتور تبدیل انجام دهید تا گزارش‌های تراکنش به صورت خودکار به این بخش اضافه شوند.",
        "from_label" to "از",
        "to_label" to "به",
        "clear_btn" to "پاک کردن",
        "online_mode_title" to "بروزرسانی آنلاین",
        "online_mode_desc" to "ویژگی‌های آنلاین در به‌روزرسانی‌های آینده اضافه خواهند شد.",
        "online_mode_subdesc" to "ارتقاهای آینده نرخ‌های زنده بانک مرکزی، نمودارهای بازار جهانی و همگام‌سازی خودکار دیتابیس را به این بخش می‌آورند.",
        "delete_currency" to "حذف ارز",
        "currency_name_placeholder" to "مانند دلار، بیت کوین...",
        "currency_note_label" to "یادداشت‌ها",
        "currency_note_placeholder" to "مثال: یادداشت‌های نرخ گمرک یا بازار آزاد",
        "currency_rate_error" to "ارزش مبادلاتی وارد شده باید عددی مثبت باشد.",
        "calc_with_app_title" to "ماشین حساب %s",
        "use_value_btn" to "پست کردن قیمت",
        "math_error" to "خطای ریاضی",

        "curr_USD" to "دلار آمریکا",
        "curr_TOMAN" to "تومان ایران",
        "curr_RIAL" to "ریال ایران",
        "curr_EUR" to "یورو",
        "curr_GBP" to "پوند انگلیس",
        "curr_AFN" to "افغانی افغانستان",
        "curr_BTC" to "بیت کوین",
        "curr_TON" to "تون کوین",
        "curr_ETH" to "اتریوم",
        "curr_SOL" to "سولانا",
        "curr_BNB" to "بایننس کوین",
        "curr_ADA" to "کاردانو",
        "curr_DOGE" to "دوج کوین",
        "curr_XRP" to "ریپل",
        "curr_USDT" to "تتر دلار",
        "curr_USDC" to "یواس‌دی کوین",
        "curr_LTC" to "لایت کوین",
        "curr_LINK" to "چین لینک",
        "curr_DOT" to "پولکادات",
        "curr_POL" to "پالیگان",
        "curr_SHIB" to "شیبا اینو",
        "curr_AVAX" to "آوالانچ",
        "curr_JPY" to "ین ژاپن",
        "curr_CAD" to "دلار کانادا",
        "curr_CHF" to "فرانک سوئیس",
        "curr_CNY" to "یوان چین",
        "curr_TRY" to "لیر ترکیه",
        "curr_AED" to "درهم امارات",
        "curr_AUD" to "دلار استرالیا",
        "curr_TJS" to "سامانی تاجیکستان",
        "curr_SAR" to "ریال عربستان",
        "curr_KWD" to "دینار کویت",
        "curr_QAR" to "ریال قطر",
        "curr_OMR" to "ریال عمان",
        "curr_BHD" to "دینار بحرین",
        "curr_IQD" to "دینار عراق",
        "curr_SYP" to "لیر سوریه",
        "curr_LBP" to "لیر لبنان",
        "curr_JOD" to "دینار اردن",
        "curr_EGP" to "پوند مصر",
        "curr_YER" to "ریال yemen",
        "curr_KZT" to "تنگه قزاقستان",
        "curr_UZS" to "سوم ازبکستان",
        "curr_AZN" to "منات آذربایجان",
        "curr_AMD" to "درام ارمنستان",
        "curr_GEL" to "لاری گرجستان",
        "curr_ILS" to "شکل اسرائیل",
        "curr_DZD" to "دینار الجزایر",
        "curr_MAD" to "درهم مراکش",
        "curr_LYD" to "دینار لیبی",
        "curr_TND" to "دینار تونس",
        "curr_SDG" to "پوند سودان",
        "curr_INR" to "روپیه هند",
        "curr_RUB" to "روبل روسیه",
        "curr_PKR" to "روپیه پاکستان",
        "curr_BRL" to "رئال برزیل",
        "curr_ZAR" to "رند آفریقای جنوبی",
        "curr_SGD" to "دلار سنگاپور",
        "curr_NZD" to "دلار نیوزیلند",
        "curr_KRW" to "وون کره جنوبی",
        "curr_MXN" to "پزو مکزیک",
        "curr_GOLD" to "اونس طلای جهانی",
        "curr_GOLD_24K" to "طلای عیار ۲۴ (گرم)",
        "curr_GOLD_18K" to "طلای عیار ۱۸ (گرم)",
        "curr_SILVER" to "اونس نقره جهانی",
        "curr_DIAMOND" to "الماس قیمتی (قیراط)",
        "curr_PLATINUM" to "اونس پلاتین جهانی",

        "tab_online" to "بروزرسانی آنلاین",
        "creator_label" to "سازنده",
        "support_dev_title" to "💝 حمایت از توسعه‌دهنده",
        "support_dev_desc" to "اگر از این برنامه لذت می‌برید و مایلید از توسعه آن حمایت کنید، می‌توانید از طریق آدرس کیف‌پول زیر هدیه اختیاری خود را ارسال کنید. حمایت شما به بهبود و نگهداری برنامه کمک می‌کند. از لطف و حمایت شما سپاسگزاریم ❤️",
        "wallet_copied_msg" to "آدرس کیف‌پول کپی شد!",
        "support_dev_warning" to "⚠️ فقط ارز USDT (BEP20) به این آدرس ارسال کنید. ارسال سایر دارایی‌ها یا شبکه‌ها ممکن است منجر به از بین رفتن دائمی وجه شود.",
        "secret_panel_title" to "بخش تنظیمات مخفی",
        "secret_panel_desc" to "شما با موفقیت وارد بخش تنظیمات مخفی شدید. در این بخش می‌توانید رمز عبور ورود را تغییر دهید.",
        "change_pass_title" to "تغییر رمز عبور ورود",
        "new_pass_placeholder" to "رمز عبور جدید...",
        "change_app_name_title" to "تغییر نام اپلیکیشن",
        "new_app_name_placeholder" to "نام جدید برنامه...",
        "change_app_icon_title" to "تغییر آیکون برنامه",
        "picked_img_preview" to "پیش‌نمایش تصویر انتخاب شده",
        "save_apply_log" to "ذخیره تغییرات",
        "support_wallet_settings" to "تنظیمات بخش حمایت مالی",
        "enable_support_section" to "فعال بودن بخش حمایت مالی",
        "change_wallet_address" to "تغییر آدرس والت (USDT BEP20)",
        "new_wallet_placeholder" to "آدرس والت جدید...",
        "change_wallet_qr" to "تغییر عکس QR Code والت",
        "pick_from_gallery" to "انتخاب از گالری",
        "reset_image" to "راه‌اندازی مجدد",
        "custom_text_above_wallet" to "متن بالای والت (سفارشی)",
        "custom_text_above_placeholder" to "مثال: لطفا حمایت کنید...",
        "custom_text_below_wallet" to "متن پایین والت (سفارشی)",
        "custom_text_below_placeholder" to "مثال: فقط USDT بفرستید...",
        "reset" to "بازنشانی",
        "secret_pass_title" to "رمز عبور بخش مخفی",
        "secret_pass_desc" to "لطفاً رمز عبور بخش مخفی را وارد کنید تا دسترسی فعال شود:",
        "incorrect_pass" to "رمز عبور نادرست است!",
        "verify" to "تایید",

        "online_mode_title" to "بروزرسانی آنلاین",
        "online_features_future" to "قابلیت‌های آنلاین در بروزرسانی‌های آینده اضافه خواهند شد.",
        "online_features_desc" to "بروزرسانی‌های بعدی شامل نرخ‌های زنده بانک مرکزی، نمودارهای بازارهای جهانی و هماهنگ‌سازی خودکار API با این بخش خواهد بود.",
        "fav_offline" to "آفلاین",
        "fav_online" to "آنلاین",
        "fav_online_inactive_title" to "بخش آنلاین هنوز فعال نشده است",
        "fav_online_inactive_desc" to "علاقه‌مندی‌های بخش آنلاین پس از فعال‌سازی این بخش در به‌روزرسانی‌های آینده در اینجا نمایش داده خواهند شد.",
        "online_sync_loading" to "در حال دریافت نرخ‌های زنده از بازارهای مالی...",
        "online_sync_success" to "بروزرسانی موفقیت‌آمیز بود! تمامی نرخ‌ها با آخرین تغییرات بازار هماهنگ شدند.",
        "online_sync_tooltip" to "بروزرسانی آنلاین نرخ‌ها",
        "tab_crypto" to "رمز ارزها",
        "tab_commodities" to "طلا، فلزات و کالاها",
        "tab_fiat" to "ارزهای بین‌المللی",
        "status_connected" to "ارتباط زنده فعال",
        "auto_update_notice" to "به‌روزرسانی خودکار هر ۶۰ ثانیه",
        "price_usd" to "قیمت دلاری: ",
        "price_base" to "معادل مبنا: ",
        "last_sync_time" to "بروزرسانی شده در: ",
        "online_no_data" to "هیچ ارزی یافت نشد. دکمه بروزرسانی را فشار دهید.",
        "market_free" to "بازار آزاد",
        "market_global" to "بازار جهانی"
    )

    private val enStrings = mapOf(
        "tab_offline" to "Offline Engine",
        "tab_favorites" to "Favorites",
        "tab_history" to "History Log",
        "tab_settings" to "Settings",
        
        "settings_header" to "Application Settings",
        "settings_desc" to "Configure display metrics, themes, localization, and advanced system options.",
        
        "currency_display_title" to "Currency Display Engine",
        "currency_display_desc" to "Set whether values are modeled in Toman or expanded to Rials formatting (1 Toman = 10 Rials).",
        "toman_label" to "Toman System Labeling (Default)",
        "rial_label" to "Rial System Labeling (Scale * 10)",
        
        "theme_title" to "User Interface Theme",
        "theme_system" to "System Default",
        "theme_light" to "Light Aesthetic",
        "theme_dark" to "Premium Dark Slate",
        
        "lang_title" to "Language Options / تغییر زبان",
        "lang_desc" to "Change the user interface language to English or Persian.",
        "lang_fa" to "فارسی (Persian)",
        "lang_en" to "English (انگلیسی)",
        
        "app_name_custom_title" to "Customize App Name",
        "app_name_custom_desc" to "Enter a personalized name for your application display:",
        "app_name_placeholder" to "App name...",
        
        "app_icon_custom_title" to "Customize App Logo/Icon",
        "app_icon_custom_desc" to "Change the displayed branding logo inside the workspace or upload a custom image:",
        "app_icon_modern" to "Modern Radiant Logo (Modern)",
        "app_icon_gold" to "Royal Imperial Gold Logo (Gold)",
        "app_icon_neon" to "Cyber Neon Digital Logo (Neon)",
        "app_icon_vintage" to "Vintage Classic Emblem (Vintage)",
        "app_icon_custom" to "Custom Gallery Icon / Loaded Successfully",
        "app_icon_gallery_btn" to "Choose Custom Image from Device Gallery",
        
        "about_title" to "About Developer & Platform",
        "about_name_label" to "Application Name:",
        "about_version_label" to "App Version:",
        "about_engine_label" to "Offline Engine:",
        "about_links_header" to "Developer Support:",
        "about_telegram" to "My Telegram Channel (@digit_bazar)",
        "about_website" to "My Personal Website",
        "about_creator" to "Creator: Mr.Maxii",
        "created_by" to "Created & Designed by: Mr.Maxii",
        
        "search_hint" to "Search code, symbol or name...",
        "add_currency" to "Add Custom Currency",
        "edit_currency" to "Edit Currency",
        "code_label" to "Currency Code (e.g. CAD)",
        "name_label" to "Full Name (e.g. Canadian Dollar)",
        "symbol_label" to "Symbol (e.g. C$)",
        "rate_label" to "Rate Relative to 1 USD",
        "save" to "Save Details",
        "cancel" to "Cancel",
        "error_invalid" to "Please enter valid parameters",
        
        "calc_title" to "Integrated Calculator Panel",
        "calc_desc" to "Evaluate mathematical expressions quickly and paste results directly to base conversion amount field.",
        "calc_hint" to "Example: 1500 * (1.10 - 0.05) + 350",
        "calc_btn" to "Paste Result to Amount Input",
        "calc_error" to "Invalid formula",
        
        // Favorites
        "fav_header" to "Favorite Currencies",
        "fav_desc" to "Pinned quick reference exchange cards. Switch reorder modes to alter displaying priority hierarchy.",
        "fav_reorder_btn" to "Toggle Reorder Mode",
        "fav_reorder_done" to "Finish Reordering",
        
        // History
        "hist_header" to "Conversion History Ledger",
        "hist_desc" to "Audit logging tracker designed for immediate tracking of exchange metrics computed in offline mode.",
        "hist_clear_btn" to "Wipe Entire History",
        "hist_empty" to "No legacy conversions in history ledger yet.",
        
        "calculator_short" to "Calculator",
        
        "sort_fav_first" to "Favorites First",
        "sort_high_val" to "Highest Value",
        "sort_low_val" to "Lowest Value",
        "sort_alpha_az" to "Alphabetical (A-Z)",
        "sort_alpha_za" to "Alphabetical (Z-A)",
        
        "sync_title" to "Sync & Restore Currencies",
        "sync_desc" to "If any default or premium commodity currencies like Gold, Silver, Diamond, Afghan, TON, etc., are missing, tap below to force-seed and recover all standard items instantly.",
        "sync_btn" to "Sync & Restore System Currencies",
        "sync_success" to "Sync successful! All system currencies are now fully populated in Room database.",
        "sync_confirm_title" to "Confirm Sync",
        "sync_confirm_msg" to "Are you sure you want to sync and restore default system currencies?",
        "yes" to "Yes",
        "no" to "No",

        "cat_all" to "All Assets 💫",
        "cat_fiat" to "Fiat Money 💵",
        "cat_crypto" to "Crypto 🪙",
        "cat_commodity" to "Gold & Gems ⚜️",

        "app_desc_headline" to "Instant Multi-Converter Live Board. Tap any rate block to choose base currency.",
        "input_placeholder" to "Enter conversion value...",
        "input_label" to "Base Conversion Amount",
        "sort_by" to "Sort By:",
        "category_label" to "Category:",
        "no_match_text" to "No matching currencies found",
        "pinned_favorites" to "PINNED FAVORITES",
        "done" to "Done",
        "edit" to "Edit",
        "fiat_header" to "FIAT CURRENCIES 💵",
        "digital_header" to "DIGITAL CURRENCIES 🪙",
        "commodity_header" to "COMMODITIES & METALS ⚜️",
        "fiat_arrow" to "Fiat 💵 ➔",
        "crypto_arrow" to "Crypto 🪙 ➔",
        "gold_arrow" to "Gold ⚜️ ➔",
        "favorites_empty_title" to "No favorites recorded yet",
        "favorites_empty_desc" to "Navigate to the 'Offline Mode' tab and tap the star icon on any currency item to pin it here.",
        "history_empty_title" to "Persistent audit ledger is empty",
        "history_empty_desc" to "Perform some offline exchange math inside the converter module to automatically generate logging cards.",
        "from_label" to "From",
        "to_label" to "To",
        "clear_btn" to "Clear",
        "online_mode_title" to "Online Mode",
        "online_mode_desc" to "Online features will be added in future updates.",
        "online_mode_subdesc" to "Future upgrades will bring real-time live central bank rates, global market charts, and automated multi-destination API syncing to this module.",
        "delete_currency" to "Delete Currency",
        "currency_name_placeholder" to "e.g. Dollar, Bitcoin",
        "currency_note_label" to "Notes (Optional)",
        "currency_note_placeholder" to "e.g. Local custom rate notes",
        "currency_rate_error" to "Exchange value must be a valid positive number.",
        "calc_with_app_title" to "%s Calculator",
        "use_value_btn" to "Use Value",
        "math_error" to "Error",

        "curr_USD" to "US Dollar",
        "curr_TOMAN" to "Iranian Toman",
        "curr_RIAL" to "Iranian Rial",
        "curr_EUR" to "Euro",
        "curr_GBP" to "Pound Sterling",
        "curr_AFN" to "Afghan Afghani",
        "curr_BTC" to "Bitcoin",
        "curr_TON" to "Toncoin",
        "curr_ETH" to "Ethereum",
        "curr_SOL" to "Solana",
        "curr_BNB" to "Binance Coin",
        "curr_ADA" to "Cardano",
        "curr_DOGE" to "Dogecoin",
        "curr_XRP" to "Ripple",
        "curr_USDT" to "Tether USD",
        "curr_USDC" to "USD Coin",
        "curr_LTC" to "Litecoin",
        "curr_LINK" to "Chainlink",
        "curr_DOT" to "Polkadot",
        "curr_POL" to "Polygon",
        "curr_SHIB" to "Shiba Inu",
        "curr_AVAX" to "Avalanche",
        "curr_JPY" to "Japanese Yen",
        "curr_CAD" to "Canadian Dollar",
        "curr_CHF" to "Swiss Franc",
        "curr_CNY" to "Chinese Yuan",
        "curr_TRY" to "Turkish Lira",
        "curr_AED" to "Emirati Dirham",
        "curr_AUD" to "Australian Dollar",
        "curr_TJS" to "Tajikistani Somoni",
        "curr_SAR" to "Saudi Riyal",
        "curr_KWD" to "Kuwaiti Dinar",
        "curr_QAR" to "Qatari Riyal",
        "curr_OMR" to "Omani Rial",
        "curr_BHD" to "Bahraini Dinar",
        "curr_IQD" to "Iraqi Dinar",
        "curr_SYP" to "Syrian Pound",
        "curr_LBP" to "Lebanese Pound",
        "curr_JOD" to "Jordanian Dinar",
        "curr_EGP" to "Egyptian Pound",
        "curr_YER" to "Yemeni Rial",
        "curr_KZT" to "Kazakhstani Tenge",
        "curr_UZS" to "Uzbekistani Som",
        "curr_AZN" to "Azerbaijani Manat",
        "curr_AMD" to "Armenian Dram",
        "curr_GEL" to "Georgian Lari",
        "curr_ILS" to "Israeli Shekel",
        "curr_DZD" to "Algerian Dinar",
        "curr_MAD" to "Moroccan Dirham",
        "curr_LYD" to "Libyan Dinar",
        "curr_TND" to "Tunisian Dinar",
        "curr_SDG" to "Sudanese Pound",
        "curr_INR" to "Indian Rupee",
        "curr_RUB" to "Russian Ruble",
        "curr_PKR" to "Pakistani Rupee",
        "curr_BRL" to "Brazilian Real",
        "curr_ZAR" to "South African Rand",
        "curr_SGD" to "Singapore Dollar",
        "curr_NZD" to "New Zealand Dollar",
        "curr_KRW" to "South Korean Won",
        "curr_MXN" to "Mexican Peso",
        "curr_GOLD" to "Gold Spot (Ounce)",
        "curr_GOLD_24K" to "Gold 24-Karat (Gram)",
        "curr_GOLD_18K" to "Gold 18-Karat (Gram)",
        "curr_SILVER" to "Silver Spot (Ounce)",
        "curr_DIAMOND" to "Diamond (Carat)",
        "curr_PLATINUM" to "Platinum (Ounce)",

        "tab_online" to "Online Mode",
        "creator_label" to "Creator",
        "support_dev_title" to "💝 Support the Developer",
        "support_dev_desc" to "If you enjoy using this app and would like to support its development, you can make an optional contribution using the wallet address below. Your support helps improve and maintain the app. Thank you for your kindness and support ❤️",
        "wallet_copied_msg" to "Wallet address copied!",
        "support_dev_warning" to "⚠️ Please send only USDT (BEP20) to this wallet address. Sending other assets or networks may result in permanent loss of funds.",
        "secret_panel_title" to "Secret Settings Panel",
        "secret_panel_desc" to "You have unlocked the secret settings panel. You can change your secret password below.",
        "change_pass_title" to "Change Secret Password",
        "new_pass_placeholder" to "New password...",
        "change_app_name_title" to "Change App Name",
        "new_app_name_placeholder" to "New app name...",
        "change_app_icon_title" to "Change App Icon Style",
        "picked_img_preview" to "Picked Image Preview",
        "save_apply_log" to "Save & Apply Log",
        "support_wallet_settings" to "Support Wallet Settings",
        "enable_support_section" to "Enable Support Section",
        "change_wallet_address" to "Change Wallet Address",
        "new_wallet_placeholder" to "New wallet address...",
        "change_wallet_qr" to "Change Wallet QR Code",
        "pick_from_gallery" to "Pick from Gallery",
        "reset_image" to "Reset Image",
        "custom_text_above_wallet" to "Custom Text Above Wallet",
        "custom_text_above_placeholder" to "E.g., Please support standard development...",
        "custom_text_below_wallet" to "Custom Text Below Wallet",
        "custom_text_below_placeholder" to "E.g., Only BEP20 USDT supported...",
        "reset" to "Reset",
        "secret_pass_title" to "Secret Section Password",
        "secret_pass_desc" to "Please enter the secret password to unlock this section:",
        "incorrect_pass" to "Incorrect Password!",
        "verify" to "Verify",

        "online_mode_title" to "Online Mode",
        "online_features_future" to "Online features will be added in future updates.",
        "online_features_desc" to "Future upgrades will bring real-time live bank rates, global market charts, and automated API syncing to this module.",
        "fav_offline" to "Offline",
        "fav_online" to "Online",
        "fav_online_inactive_title" to "Online Mode is Not Active Yet",
        "fav_online_inactive_desc" to "Your online section favorites will appear here once the online mode is enabled in future updates.",
        "online_sync_loading" to "Connecting to financial APIs and fetching live rates...",
        "online_sync_success" to "Update successful! All exchange rates synced with the latest live market values.",
        "online_sync_tooltip" to "Update rates online",
        "tab_crypto" to "Cryptocurrencies",
        "tab_commodities" to "Precious Metals & Commodities",
        "tab_fiat" to "Fiat Currencies",
        "status_connected" to "Live Connection Active",
        "auto_update_notice" to "Auto-updates every 60s",
        "price_usd" to "USD Price: ",
        "price_base" to "Base Equivalent: ",
        "last_sync_time" to "Last Updated: ",
        "online_no_data" to "No exchange rate data found. Press sync.",
        "market_free" to "Free Market",
        "market_global" to "Global Market"
    )

    private val arStrings = mapOf(
        "tab_offline" to "محرك التحويل بدون إنترنت",
        "tab_favorites" to "المفضلة",
        "tab_history" to "سجل التحويلات",
        "tab_settings" to "الإعدادات",
        "settings_header" to "إعدادات التطبيق",
        "settings_desc" to "تكوين مقاييس العرض والسمات واللغات وخيارات النظام المتقدمة.",
        "currency_display_title" to "محرك عرض العملة",
        "currency_display_desc" to "اختر ما إذا كان العرض بالتومان أو الريال (1 تومان = 10 ريال).",
        "toman_label" to "نظام التومان (افتراضي)",
        "rial_label" to "نظام الريال (ضرب 10)",
        "theme_title" to "سمة واجهة المستخدم",
        "theme_system" to "افتراضي النظام",
        "theme_light" to "المظهر الفاتح",
        "theme_dark" to "المظهر الداكن الفاخر",
        "lang_title" to "خيارات اللغة / Language",
        "lang_desc" to "تغيير لغة واجهة المستخدم للتطبيق.",
        "lang_fa" to "فارسي (Persian)",
        "lang_en" to "English (إنكليزي)",
        "lang_ar" to "العربية (Arabic)",
        "lang_zh" to "中文 (Chinese)",
        "lang_de" to "Deutsch (German)",
        "lang_tr" to "Türkçe (Turkish)",
        "lang_fr" to "Français (French)",
        "about_title" to "حول المطور والمنصة",
        "about_name_label" to "اسم التطبيق:",
        "about_version_label" to "الإصدار:",
        "about_engine_label" to "المحرك المحلي:",
        "about_links_header" to "قنوات التواصل الدعم:",
        "about_telegram" to "قناتي على تلغرام (@digit_bazar)",
        "about_website" to "موقعي الشخصي",
        "search_hint" to "البحث عن عملة أو رمز...",
        "add_currency" to "إضافة عملة مخصصة",
        "edit_currency" to "تعديل العملة",
        "save" to "حفظ التغييرات",
        "cancel" to "إلغاء",
        "sync_title" to "المزامنة واستعادة العملات",
        "sync_desc" to "إذا كانت العملات الافتراضية مفقودة، انقر أدناه لإعادة تهيئة جميع العناصر فوراً.",
        "sync_btn" to "مزامنة واستعادة عملات النظام",
        "sync_success" to "تمت المزامنة بنجاح!",

        "app_desc_headline" to "محرک التحويل المباشر متعدد العملات. اضغط على أي فئة لتحديد العملة الأساسية.",
        "input_placeholder" to "أدخل القيمة للتحويل...",
        "input_label" to "مبلغ التحويل الأساسي",
        "sort_by" to "ترتيب حسب:",
        "category_label" to "الفئة:",
        "no_match_text" to "لم يتم العثور على عملات مطابقة",
        "pinned_favorites" to "العملات المفضلة المثبتة",
        "done" to "تم",
        "edit" to "تعديل",
        "fiat_header" to "العملات التقليدية (العادية) 💵",
        "digital_header" to "العملات الرقمية (المشفرة) 🪙",
        "commodity_header" to "الذهب والسلع والمعادن الثمينة ⚜️",
        "fiat_arrow" to "فیات 💵 ➔",
        "crypto_arrow" to "رقمي 🪙 ➔",
        "gold_arrow" to "ذهب/سلع ⚜️ ➔",
        "favorites_empty_title" to "لم يتم تسجيل أي عملة مفضلة بعد",
        "favorites_empty_desc" to "انتقل إلى علامة التبويب 'محرك التحويل' واضغط على أيقونة النجمة لتثبيتها هنا.",
        "history_empty_title" to "سجل المعاملات فارغ حالياً",
        "history_empty_desc" to "قم بإجراء بعض العمليات الحسابية في محرك التحويل ليتم تسجيلها هنا تلقائياً.",
        "from_label" to "من",
        "to_label" to "إلى",
        "clear_btn" to "مسح",
        "online_mode_title" to "التحديث المتصل",
        "online_mode_desc" to "سيتم إضافة الميزات عبر الإنترنت في التحديثات القادمة.",
        "online_mode_subdesc" to "ستجلب الترقيات المستقبلية أسعار البنك المركزي الحية، ومخططات السوق العالمية، والمزامنة التلقائية.",
        "delete_currency" to "حذف العملة",
        "currency_name_placeholder" to "مثل دولار، بيتكوين...",
        "currency_note_label" to "ملاحظات (اختياري)",
        "currency_note_placeholder" to "مثال: ملاحظات سعر الجمرك أو السوق الحرة",
        "currency_rate_error" to "يجب أن تكون قيمة الصرف can رقماً موجباً.",
        "calc_with_app_title" to "حاسبة %s",
        "use_value_btn" to "استخدام القيمة",
        "math_error" to "خطأ رياضي",

        "curr_USD" to "دولار أمريكي",
        "curr_TOMAN" to "تومان إيراني",
        "curr_RIAL" to "ريال إيراني",
        "curr_EUR" to "يورو",
        "curr_GBP" to "جنيه إسترليني",
        "curr_AFN" to "أفغاني أفغانستان",
        "curr_BTC" to "بيتكوين",
        "curr_TON" to "تون كوين",
        "curr_ETH" to "إيثيريوم",
        "curr_SOL" to "سولانا",
        "curr_BNB" to "بينانس كوين",
        "curr_ADA" to "كاردانو",
        "curr_DOGE" to "دوج كوين",
        "curr_XRP" to "ريبيل",
        "curr_USDT" to "تيثر",
        "curr_USDC" to "يو إس دي كوين",
        "curr_LTC" to "لايت كوين",
        "curr_LINK" to "تشينلينك",
        "curr_DOT" to "بولكادوت",
        "curr_POL" to "بوليجون",
        "curr_SHIB" to "شيبا إينو",
        "curr_AVAX" to "أفالانش",
        "curr_JPY" to "ين ياباني",
        "curr_CAD" to "دولار كندي",
        "curr_CHF" to "فرنك سويسري",
        "curr_CNY" to "يوان صيني",
        "curr_TRY" to "ليرة تركية",
        "curr_AED" to "درهم إماراتي",
        "curr_AUD" to "دولار أسترالي",
        "curr_TJS" to "ساماني طاجيكي",
        "curr_SAR" to "ريال سعودي",
        "curr_KWD" to "دينار كويتي",
        "curr_QAR" to "ريال قطري",
        "curr_OMR" to "ريال عماني",
        "curr_BHD" to "دينار بحريني",
        "curr_IQD" to "دينار عراقي",
        "curr_SYP" to "ليرة سورية",
        "curr_LBP" to "ليرة لبنانية",
        "curr_JOD" to "دينار أردني",
        "curr_EGP" to "جنيه مصري",
        "curr_YER" to "ريال يمني",
        "curr_KZT" to "تينغ كازاخستاني",
        "curr_UZS" to "سوم أوزبكستاني",
        "curr_AZN" to "مانات أذربيجاني",
        "curr_AMD" to "درام أرميني",
        "curr_GEL" to "لاري جورجي",
        "curr_ILS" to "شيكل إسرائيلي",
        "curr_DZD" to "دينار جزائري",
        "curr_MAD" to "درهم مغربي",
        "curr_LYD" to "دينار ليبي",
        "curr_TND" to "دينار تونسي",
        "curr_SDG" to "جنيه سوداني",
        "curr_INR" to "روبية هندية",
        "curr_RUB" to "روبل روسي",
        "curr_PKR" to "روبية باكستانية",
        "curr_BRL" to "ريال برازيلي",
        "curr_ZAR" to "راند جنوب أفريقي",
        "curr_SGD" to "دولار سنغافوري",
        "curr_NZD" to "دولار نيوزيلندي",
        "curr_KRW" to "وون كوري جنوبي",
        "curr_MXN" to "بيزو مكسيكي",
        "curr_GOLD" to "أونصة الذهب",
        "curr_GOLD_24K" to "ذهب عيار 24 (جرام)",
        "curr_GOLD_18K" to "ذهب عيار 18 (جرام)",
        "curr_SILVER" to "أونصة الفضة",
        "curr_DIAMOND" to "أونصة الألماس",
        "curr_PLATINUM" to "أونصة البلاتين",

        "tab_online" to "التحديث أونلاين",
        "creator_label" to "المنشئ",
        "support_dev_title" to "💝 دعم المطور",
        "support_dev_desc" to "إذا كنت تستمتع باستخدام هذا التطبيق وترغب في دعم تطويره، يمكنك تقديم مساهمة اختيارية باستخدام عنوان المحفظة أدناه. يساعد دعمك في تحسين التطبيق وصيانته. شكرًا لك على لطفك ودعمك ❤️",
        "wallet_copied_msg" to "تم نسخ عنوان المحفظة!",
        "support_dev_warning" to "⚠️ يرجى إرسال USDT (BEP20) فقط إلى عنوان هذه المحفظة. قد يؤدي إرسال أصول أو شبكات أخرى إلى فقدان الأموال بشكل دائم.",
        "secret_panel_title" to "لوحة الإعدادات السرية",
        "secret_panel_desc" to "لقد قمت بفتح لوحة الإعدادات السرية. يمكنك تغيير كلمتك السرية أدناه.",
        "change_pass_title" to "تغيير كلمة المرور السرية",
        "new_pass_placeholder" to "كلمة مرور جديدة...",
        "change_app_name_title" to "تغيير اسم التطبيق",
        "new_app_name_placeholder" to "اسم التطبيق الجديد...",
        "change_app_icon_title" to "تغيير ستايل أيقونة التطبيق",
        "picked_img_preview" to "معاينة الصورة المحددة",
        "save_apply_log" to "حفظ وتطبيق التغييرات",
        "support_wallet_settings" to "إعدادات محفظة الدعم",
        "enable_support_section" to "تمكين قسم الدعم",
        "change_wallet_address" to "تغيير عنوان المحفظة",
        "new_wallet_placeholder" to "عنوان المحفظة الجديد...",
        "change_wallet_qr" to "تغيير رمز الاستجابة السريعة (QR)",
        "pick_from_gallery" to "اختيار من المعرض",
        "reset_image" to "إعادة تعيين الصورة",
        "custom_text_above_wallet" to "نص مخصص فوق المحفظة",
        "custom_text_above_placeholder" to "مثال: يرجى تقديم الدعم...",
        "custom_text_below_wallet" to "نص مخصص أسفل المحفظة",
        "custom_text_below_placeholder" to "مثال: يُقبل فقط USDT (BEP20)...",
        "reset" to "إعادة ضبط",
        "secret_pass_title" to "كلمة مرور القسم السري",
        "secret_pass_desc" to "يرجى إدخال كلمة المرور السرية لفتح هذا القسم:",
        "incorrect_pass" to "كلمة مرور خاطئة!",
        "verify" to "تأكيد",

        "online_mode_title" to "التحديث أونلاين",
        "online_features_future" to "سيتم إضافة الميزات عبر الإنترنت في التحديثات القادمة.",
        "online_features_desc" to "ستجلب الترقيات المستقبلية أسعار البنوك الحية في الوقت الفعلي ومخططات السوق العالمية ومزامنة واجهة برمجة التطبيقات الآلية إلى هذه الوحدة."
    )

    private val zhStrings = mapOf(
        "tab_offline" to "离线换算引擎",
        "tab_favorites" to "自选收藏",
        "tab_history" to "兑换历史记录",
        "tab_settings" to "系统设置",
        "settings_header" to "软件应用设置",
        "settings_desc" to "配置货币显示单位、界面主题、语言本地化以及高级系统选项。",
        "currency_display_title" to "货币计算显示模式",
        "currency_display_desc" to "设置显示单位为 托曼(Toman) 或 里亚尔(Rial) (1 托曼 = 10 里亚尔)。",
        "toman_label" to "托曼系统 (默认)",
        "rial_label" to "里亚尔系统 (乘以 10)",
        "theme_title" to "界面显示主题",
        "theme_system" to "系统默认",
        "theme_light" to "优雅浅色",
        "theme_dark" to "奢华深色",
        "lang_title" to "语言选择 / Language",
        "lang_desc" to "更改应用程序的显示语言。",
        "lang_fa" to "فارسی (波斯语)",
        "lang_en" to "English (英语)",
        "lang_ar" to "العربية (阿拉伯语)",
        "lang_zh" to "简体中文 (Chinese)",
        "lang_de" to "Deutsch (德语)",
        "lang_tr" to "Türkçe (土耳其语)",
        "lang_fr" to "Français (法语)",
        "about_title" to "关于开发者与平台",
        "about_name_label" to "应用名称:",
        "about_version_label" to "应用版本:",
        "about_engine_label" to "本地引擎:",
        "about_links_header" to "联系开发者:",
        "about_telegram" to "我的电报频道 (@digit_bazar)",
        "about_website" to "我的个人网站",
        "search_hint" to "搜索货币代码或名称...",
        "add_currency" to "添加自定义货币",
        "edit_currency" to "编辑货币信息",
        "save" to "保存修改",
        "cancel" to "取消",
        "sync_title" to "同步与恢复系统货币",
        "sync_desc" to "如果丢失了默认系统货币，请点击下方按钮立即重新加载和恢复。",
        "sync_btn" to "重建并同步系统默认货币",
        "sync_success" to "系统货币同步成功！",

        "app_desc_headline" to "多货币实时离线换算引擎。点击任意汇率框可切换基准货币。",
        "input_placeholder" to "输入要换算的金额...",
        "input_label" to "基准换算金额",
        "sort_by" to "排序方式:",
        "category_label" to "分类:",
        "no_match_text" to "未找到符合条件的货币",
        "pinned_favorites" to "已固定收藏",
        "done" to "完成",
        "edit" to "编辑",
        "fiat_header" to "经典法定货币 💵",
        "digital_header" to "数字加密货币 🪙",
        "commodity_header" to "黄金、大宗商品与贵金属 ⚜️",
        "fiat_arrow" to "法币 💵 ➔",
        "crypto_arrow" to "数字币 🪙 ➔",
        "gold_arrow" to "黄金/商品 ⚜️ ➔",
        "favorites_empty_title" to "暂无自选收藏货币",
        "favorites_empty_desc" to "请前往“离线工具”页面，点击任意货币上的星标即可在此显示。",
        "history_empty_title" to "兑换历史记录为空",
        "history_empty_desc" to "在转换工具中进行一些离线计算，换算日志便会自动呈现在这里。",
        "from_label" to "从",
        "to_label" to "到",
        "clear_btn" to "清除",
        "online_mode_title" to "在线模式",
        "online_mode_desc" to "在线实时功能将在后续版本中推出。",
        "online_mode_subdesc" to "未来的升级将为此模块带来实时中央银行汇率、全球市场图表和自动 API 同步功能。",
        "delete_currency" to "删除货币",
        "currency_name_placeholder" to "例如：美元、比特币",
        "currency_note_label" to "备注 (可选)",
        "currency_note_placeholder" to "例如：海关汇率或自由市场汇率备注",
        "currency_rate_error" to "汇率必须是有效的正数。",
        "calc_with_app_title" to "%s 计算器",
        "use_value_btn" to "使用数值",
        "math_error" to "数学错误",

        "curr_USD" to "美元",
        "curr_TOMAN" to "伊朗托曼",
        "curr_RIAL" to "伊朗里亚尔",
        "curr_EUR" to "欧元",
        "curr_GBP" to "英镑",
        "curr_AFN" to "阿富汗尼",
        "curr_BTC" to "比特币",
        "curr_TON" to "吨币 / Toncoin",
        "curr_ETH" to "以太坊",
        "curr_SOL" to "索拉纳",
        "curr_BNB" to "币安币",
        "curr_ADA" to "艾达币",
        "curr_DOGE" to "狗狗币",
        "curr_XRP" to "瑞波币",
        "curr_USDT" to "泰达币",
        "curr_USDC" to "美金硬币",
        "curr_LTC" to "莱特币",
        "curr_LINK" to "链 link",
        "curr_DOT" to "波卡币",
        "curr_POL" to "多边形 / Polygon",
        "curr_SHIB" to "柴犬币",
        "curr_AVAX" to "雪崩币",
        "curr_JPY" to "日元",
        "curr_CAD" to "加元",
        "curr_CHF" to "瑞士法郎",
        "curr_CNY" to "人民币",
        "curr_TRY" to "土耳其里拉",
        "curr_AED" to "阿联酋迪拉姆",
        "curr_AUD" to "澳元",
        "curr_TJS" to "塔吉克索莫尼",
        "curr_SAR" to "沙特里亚尔",
        "curr_KWD" to "科威特第纳尔",
        "curr_QAR" to "卡塔尔里亚尔",
        "curr_OMR" to "阿曼里亚尔",
        "curr_BHD" to "巴林第纳尔",
        "curr_IQD" to "伊拉克第纳尔",
        "curr_SYP" to "叙利亚镑",
        "curr_LBP" to "黎巴嫩镑",
        "curr_JOD" to "约旦第纳尔",
        "curr_EGP" to "埃及镑",
        "curr_YER" to "叶门里亚尔",
        "curr_KZT" to "哈萨克坚戈",
        "curr_UZS" to "乌兹别克索姆",
        "curr_AZN" to "阿塞拜疆马纳特",
        "curr_AMD" to "亚美尼亚德拉姆",
        "curr_GEL" to "格鲁吉亚拉里",
        "curr_ILS" to "以色列新谢克尔",
        "curr_DZD" to "阿尔及利亚第纳尔",
        "curr_MAD" to "摩洛哥迪拉姆",
        "curr_LYD" to "利比亚第纳尔",
        "curr_TND" to "突尼斯第纳尔",
        "curr_SDG" to "苏丹镑",
        "curr_INR" to "印度卢比",
        "curr_RUB" to "俄罗斯卢布",
        "curr_PKR" to "巴基斯坦卢比",
        "curr_BRL" to "巴西雷亚尔",
        "curr_ZAR" to "南非兰特",
        "curr_SGD" to "新加坡元",
        "curr_NZD" to "新西兰元",
        "curr_KRW" to "韩元",
        "curr_MXN" to "墨西哥比索",
        "curr_GOLD" to "黄金现货（盎司）",
        "curr_GOLD_24K" to "足金24K（克）",
        "curr_GOLD_18K" to "18K金（克）",
        "curr_SILVER" to "白银现货（盎司）",
        "curr_DIAMOND" to "钻石（克拉）",
        "curr_PLATINUM" to "铂金现货（盎司）",

        "tab_online" to "在线模式",
        "creator_label" to "创建者",
        "support_dev_title" to "💝 支持开发者",
        "support_dev_desc" to "如果您喜欢使用此应用程序并希望支持其开发，您可以使用下方的钱包地址进行自愿赞助。您的支持有助于改进和维护该应用程序。感谢您的慷慨和支持 ❤️",
        "wallet_copied_msg" to "钱包地址已复制！",
        "support_dev_warning" to "⚠️ 请仅向此钱包地址发送 USDT (BEP20)。发送其他资产或网络可能会导致资金永久丢失。",
        "secret_panel_title" to "隐藏设置面板",
        "secret_panel_desc" to "您已解锁隐藏设置面板。您可以在下方更改隐藏密码。",
        "change_pass_title" to "更改隐藏密码",
        "new_pass_placeholder" to "新密码...",
        "change_app_name_title" to "更改应用名称",
        "new_app_name_placeholder" to "新应用名称...",
        "change_app_icon_title" to "更改应用图标样式",
        "picked_img_preview" to "所选图片预览",
        "save_apply_log" to "保存并应用更改",
        "support_wallet_settings" to "支持赞助钱包设置",
        "enable_support_section" to "启用支持赞助区域",
        "change_wallet_address" to "更改钱包地址",
        "new_wallet_placeholder" to "新钱包地址...",
        "change_wallet_qr" to "更改钱包 QR 码图片",
        "pick_from_gallery" to "从相册中选取",
        "reset_image" to "重置图片",
        "custom_text_above_wallet" to "钱包上方自定义文本",
        "custom_text_above_placeholder" to "例如：感谢赞助，支持我们的日常维护与升级...",
        "custom_text_below_wallet" to "钱包下方自定义文本",
        "custom_text_below_placeholder" to "例如：仅限支持 BEP20 链上的 USDT 类型...",
        "reset" to "重置",
        "secret_pass_title" to "输入隐藏区域密码",
        "secret_pass_desc" to "请输入隐藏密码以解锁此专属隐藏区域：",
        "incorrect_pass" to "密码输入错误！",
        "verify" to "确认验证",

        "online_mode_title" to "在线模式",
        "online_features_future" to "在线功能将在未来的更新中提供。",
        "online_features_desc" to "未来的升级将为此模块带来实时活水利率、全球市场图表以及自动化 API 同步。"
    )

    private val deStrings = mapOf(
        "tab_offline" to "Offline-Rechner",
        "tab_favorites" to "Favoriten",
        "tab_history" to "Ergebnis-Verlauf",
        "tab_settings" to "Einstellungen",
        "settings_header" to "App-Einstellungen",
        "settings_desc" to "Konfigurieren Sie Anzeigeeinheiten, Farbthemen, Lokalisierung und Systemschnittstellen.",
        "currency_display_title" to "Währungsrechner-Modus",
        "currency_display_desc" to "Bestimmen Sie, ob Beträge in Toman oder Rial (1 Toman = 10 Rial) angezeigt werden.",
        "toman_label" to "Toman-System (Standard)",
        "rial_label" to "Rial-System (Faktor 10)",
        "theme_title" to "Erscheinungsbild",
        "theme_system" to "Systemstandard",
        "theme_light" to "Helles Design",
        "theme_dark" to "Premium-Dunkelmodus",
        "lang_title" to "Spracheinstellungen / Language",
        "lang_desc" to "Ändern Sie die Sprache für die Benutzeroberfläche.",
        "lang_fa" to "فارسی (Persisch)",
        "lang_en" to "English (Englisch)",
        "lang_ar" to "العربية (Arabisch)",
        "lang_zh" to "中文 (Chinesisch)",
        "lang_de" to "Deutsch (German)",
        "lang_tr" to "Türkçe (Türkisch)",
        "lang_fr" to "Français (Französisch)",
        "about_title" to "Über den Entwickler & Plattform",
        "about_name_label" to "Anwendungsname:",
        "about_version_label" to "Version:",
        "about_engine_label" to "Lokale Engine:",
        "about_links_header" to "Support & Kontakt:",
        "about_telegram" to "Mein Telegram-Kanal (@digit_bazar)",
        "about_website" to "Meine Webseite",
        "search_hint" to "Währung oder Symbol suchen...",
        "add_currency" to "Eigene Währung hinzufügen",
        "edit_currency" to "Währung bearbeiten",
        "save" to "Änderungen speichern",
        "cancel" to "Abbrechen",
        "sync_title" to "Währungen synchronisieren & wiederherstellen",
        "sync_desc" to "Falls Standardwährungen fehlen, klicken Sie unten, um das System neu zu laden.",
        "sync_btn" to "Systemwährungen jetzt wiederherstellen",
        "sync_success" to "Synchronisierung erfolgreich abgeschlossen!",

        "app_desc_headline" to "Direkter Multi-Währungsumrechner. Tippen Sie auf einen Block, um die Basiswährung zu wählen.",
        "input_placeholder" to "Geben Sie einen Betrag ein...",
        "input_label" to "Basisbetrag",
        "sort_by" to "Sortieren nach:",
        "category_label" to "Kategorie:",
        "no_match_text" to "Keine übereinstimmenden Währungen gefunden",
        "pinned_favorites" to "ANGEHEFTETE FAVORITEN",
        "done" to "Fertig",
        "edit" to "Bearbeiten",
        "fiat_header" to "FIAT-WÄHRUNGEN 💵",
        "digital_header" to "DIGITALE WÄHRUNGEN 🪙",
        "commodity_header" to "ROHSTOFFE & EDELMETALLE ⚜️",
        "fiat_arrow" to "Fiat 💵 ➔",
        "crypto_arrow" to "Crypto 🪙 ➔",
        "gold_arrow" to "Gold ⚜️ ➔",
        "favorites_empty_title" to "Noch keine Favoriten gespeichert",
        "favorites_empty_desc" to "Wechseln Sie zum 'Offline-Rechner' und tippen Sie auf den Stern eines Elements, um es hier anzuheften.",
        "history_empty_title" to "Keine Logeinträge vorhanden",
        "history_empty_desc" to "Führen Sie Berechnungen im Rechner aus, damit diese hier automatisch protokolliert werden.",
        "from_label" to "Von",
        "to_label" to "An",
        "clear_btn" to "Löschen",
        "online_mode_title" to "Online-Modus",
        "online_mode_desc" to "Online-Funktionen werden in zukünftigen Updates hinzugefügt.",
        "online_mode_subdesc" to "Zukünftige Updates bringen Echtzeit-Zentralbankkurse, globale Marktcharts und automatische API-Synchronisierung.",
        "delete_currency" to "Währung löschen",
        "currency_name_placeholder" to "z.B. Dollar, Bitcoin",
        "currency_note_label" to "Notizen (Optional)",
        "currency_note_placeholder" to "z.B. Lokale Zoll- oder Marktnotizen",
        "currency_rate_error" to "Der Umrechnungskurs muss eine positive Zahl sein.",
        "calc_with_app_title" to "%s Rechner",
        "use_value_btn" to "Wert verwenden",
        "math_error" to "Mathematischer Fehler",

        "curr_USD" to "US-Dollar",
        "curr_TOMAN" to "Iranischer Toman",
        "curr_RIAL" to "Iranischer Rial",
        "curr_EUR" to "Euro",
        "curr_GBP" to "Britisches Pfund",
        "curr_AFN" to "Afghanischer Afghani",
        "curr_BTC" to "Bitcoin",
        "curr_TON" to "Toncoin",
        "curr_ETH" to "Ethereum",
        "curr_SOL" to "Solana",
        "curr_BNB" to "Binance Coin",
        "curr_ADA" to "Cardano",
        "curr_DOGE" to "Dogecoin",
        "curr_XRP" to "Ripple",
        "curr_USDT" to "Tether USD",
        "curr_USDC" to "USD Coin",
        "curr_LTC" to "Litecoin",
        "curr_LINK" to "Chainlink",
        "curr_DOT" to "Polkadot",
        "curr_POL" to "Polygon",
        "curr_SHIB" to "Shiba Inu",
        "curr_AVAX" to "Avalanche",
        "curr_JPY" to "Japanischer Yen",
        "curr_CAD" to "Kanadischer Dollar",
        "curr_CHF" to "Schweizer Franken",
        "curr_CNY" to "Chinesischer Yuan",
        "curr_TRY" to "Türkische Lira",
        "curr_AED" to "VAE-Dirham",
        "curr_AUD" to "Australischer Dollar",
        "curr_TJS" to "Tadschikistan-Somoni",
        "curr_SAR" to "Saudi-Riyal",
        "curr_KWD" to "Kuwait-Dinar",
        "curr_QAR" to "Katar-Riyal",
        "curr_OMR" to "Omanischer Rial",
        "curr_BHD" to "Bahrain-Dinar",
        "curr_IQD" to "Irakischer Dinar",
        "curr_SYP" to "Syrisches Pfund",
        "curr_LBP" to "Libanesisches Pfund",
        "curr_JOD" to "Jordanischer Dinar",
        "curr_EGP" to "Ägyptisches Pfund",
        "curr_YER" to "Jemen-Rial",
        "curr_KZT" to "Kasachischer Tenge",
        "curr_UZS" to "Usbekistan-Sum",
        "curr_AZN" to "Aserbaidschan-Manat",
        "curr_AMD" to "Armenischer Dram",
        "curr_GEL" to "Georgischer Lari",
        "curr_ILS" to "Israelischer Schekel",
        "curr_DZD" to "Algerischer Dinar",
        "curr_MAD" to "Marokkanischer Dirham",
        "curr_LYD" to "Libyscher Dinar",
        "curr_TND" to "Tunesischer Dinar",
        "curr_SDG" to "Sudanesisches Pfund",
        "curr_INR" to "Indische Rupie",
        "curr_RUB" to "Russischer Rubel",
        "curr_PKR" to "Pakistanische Rupie",
        "curr_BRL" to "Brasilianischer Real",
        "curr_ZAR" to "Südafrikanischer Rand",
        "curr_SGD" to "Singapur-Dollar",
        "curr_NZD" to "Neuseeland-Dollar",
        "curr_KRW" to "Südkoreanischer Won",
        "curr_MXN" to "Mexikanischer Peso",
        "curr_GOLD" to "Gold Spot (Unze)",
        "curr_GOLD_24K" to "Gold 24 Karat (Gramm)",
        "curr_GOLD_18K" to "Gold 18 Karat (Gramm)",
        "curr_SILVER" to "Silber Spot (Unze)",
        "curr_DIAMOND" to "Diamant (Karat)",
        "curr_PLATINUM" to "Platin (Unze)",

        "tab_online" to "Online-Modus",
        "creator_label" to "Entwickler",
        "support_dev_title" to "💝 Entwickler unterstützen",
        "support_dev_desc" to "Wenn Ihnen diese App gefällt und Sie deren Entwicklung unterstützen möchten, können Sie über die unten stehende Wallet-Adresse einen optionalen Beitrag leisten. Ihre Unterstützung hilft, die App zu verbessern und zu pflegen. Vielen Dank für Ihre Freundlichkeit und Unterstützung ❤️",
        "wallet_copied_msg" to "Wallet-Adresse kopiert!",
        "support_dev_warning" to "⚠️ Bitte senden Sie nur USDT (BEP20) aan diese Wallet-Adresse. Das Senden anderer Assets oder über andere Netzwerke kann zu einem dauerhaften Verlust der Mittel führen.",
        "secret_panel_title" to "Geheimes Einstellungsfenster",
        "secret_panel_desc" to "Sie haben das geheime Einstellungsfenster freigeschaltet. Sie können Ihr geheimes Passwort unten ändern.",
        "change_pass_title" to "Geheimes Passwort ändern",
        "new_pass_placeholder" to "Neues Passwort...",
        "change_app_name_title" to "App-Namen ändern",
        "new_app_name_placeholder" to "Neuer App-Name...",
        "change_app_icon_title" to "App-Icon-Stil ändern",
        "picked_img_preview" to "Vorschau des ausgewählten Bildes",
        "save_apply_log" to "Speichern & übernehmen",
        "support_wallet_settings" to "Support-Wallet-Einstellungen",
        "enable_support_section" to "Support-Bereich aktivieren",
        "change_wallet_address" to "Wallet-Adresse ändern",
        "new_wallet_placeholder" to "Neue Wallet-Adresse...",
        "change_wallet_qr" to "Wallet QR-Code ändern",
        "pick_from_gallery" to "Aus Galerie auswählen",
        "reset_image" to "Bild zurücksetzen",
        "custom_text_above_wallet" to "Benutzerdefinierter Text über Wallet",
        "custom_text_above_placeholder" to "Z.B. Bitte unterstützen Sie die Entwicklung...",
        "custom_text_below_wallet" to "Benutzerdefinierter Text unter Wallet",
        "custom_text_below_placeholder" to "Z.B. Nur BEP20 USDT wird unterstützt...",
        "reset" to "Zurücksetzen",
        "secret_pass_title" to "Passwort für geheimen Bereich",
        "secret_pass_desc" to "Bitte geben Sie das geheime Passwort ein, um diesen Bereich freizuschalten:",
        "incorrect_pass" to "Falsches Passwort!",
        "verify" to "Bestätigen",

        "online_mode_title" to "Online-Modus",
        "online_features_future" to "Online-Funktionen werden in zukünftigen Updates hinzugefügt.",
        "online_features_desc" to "Zukünftige Updates bringen Echtzeit-Wechselkurse, globale Markt-Charts und automatisierte API-Synchronisierung für dieses Modul."
    )

    private val trStrings = mapOf(
        "tab_offline" to "Çevrimdışı Hesaplayıcı",
        "tab_favorites" to "Favoriler",
        "tab_history" to "İşlem Geçmişi",
        "tab_settings" to "Ayarlar",
        "settings_header" to "Uygulama Ayarları",
        "settings_desc" to "Görüntüleme birimlerini, temaları, dilleri ve gelişmiş sistem seçeneklerini yapılandırın.",
        "currency_display_title" to "Para Birimi Hesaplama Modu",
        "currency_display_desc" to "Değerlerin Tümen veya Riyal (1 Tümen = 10 Riyal) olarak gösterilmesini ayarlayın.",
        "toman_label" to "Tümen Sistemi (Varsayılan)",
        "rial_label" to "Riyal Sistemi (Ölçek * 10)",
        "theme_title" to "Arayüz Teması",
        "theme_system" to "Sistem Varsayılanı",
        "theme_light" to "Açık Tema",
        "theme_dark" to "Premium Karanlık Tema",
        "lang_title" to "Dil Seçenekleri / Language",
        "lang_desc" to "Kullanıcı arayüzü dilini değiştirin.",
        "lang_fa" to "فارسی (Farsça)",
        "lang_en" to "English (İngilizce)",
        "lang_ar" to "العربية (Arapça)",
        "lang_zh" to "中文 (Çince)",
        "lang_de" to "Deutsch (Almanca)",
        "lang_tr" to "Türkçe (Turkish)",
        "lang_fr" to "Français (Fransızca)",
        "about_title" to "Geliştirici ve Platform Hakkında",
        "about_name_label" to "Uygulama Adı:",
        "about_version_label" to "Uygulama Sürümü:",
        "about_engine_label" to "Yerel Motor:",
        "about_links_header" to "Geliştirici İletişim:",
        "about_telegram" to "Telegram Kanalım (@digit_bazar)",
        "about_website" to "Kişisel Web Sitem",
        "search_hint" to "Para birimi kodu veya adı ara...",
        "add_currency" to "Özel Para Birimi Ekle",
        "edit_currency" to "Para Birimini Düzenle",
        "save" to "Değişiklikleri Kaydet",
        "cancel" to "İptal Et",
        "sync_title" to "Eşitle ve Para Birimlerini Geri Yükle",
        "sync_desc" to "Varsayılan para birimleri eksikse, tümünü geri yüklemek için aşağıdaki butona tıklayın.",
        "sync_btn" to "Sistem Para Birimlerini Geri Yükle",
        "sync_success" to "Eşitleme başarıyla tamamlandı!",

        "app_desc_headline" to "Anlık Çoklu Para Birimi Dönüştürücü. Temel para birimini seçmek için herhangi bir bloğa dokunun.",
        "input_placeholder" to "Dönüştürülecek tutarı girin...",
        "input_label" to "Temel Dönüşüm Tutarı",
        "sort_by" to "Sırala:",
        "category_label" to "Kategori:",
        "no_match_text" to "Eşleşen para birimi bulunamadı",
        "pinned_favorites" to "SABİTLENMİŞ FAVORİLER",
        "done" to "Tamam",
        "edit" to "Düzenle",
        "fiat_header" to "FİAT PARA BİRİMLERİ 💵",
        "digital_header" to "DİJİTAL PARA BİRİMLERİ 🪙",
        "commodity_header" to "EMTİA VE DEĞERLİ METALLER ⚜️",
        "fiat_arrow" to "Fiat 💵 ➔",
        "crypto_arrow" to "Kripto 🪙 ➔",
        "gold_arrow" to "Altın/Emtia ⚜️ ➔",
        "favorites_empty_title" to "Henüz favori eklenmedi",
        "favorites_empty_desc" to "'Çevrimdışı Reber' sekmesine gidin ve sabitlemek için yıldız simgesine dokunun.",
        "history_empty_title" to "İşlem geçmişi bomboş",
        "history_empty_desc" to "Hesaplayıcıda çevrimdışı dönüşümler yaptıkça geçmiş kartları otomatik oluşturulacaktır.",
        "from_label" to "Kimden",
        "to_label" to "Kime",
        "clear_btn" to "Temizle",
        "online_mode_title" to "Çevrimiçi Mod",
        "online_mode_desc" to "Çevrimiçi özellikler gelecekteki güncellemelerle eklenecektir.",
        "online_mode_subdesc" to "Gelecekteki güncellemeler canlı merkez bankası kurlarını, küresel piyasa grafiklerini ve otomatik güncellemeleri getirecektir.",
        "delete_currency" to "Para Birimini Sil",
        "currency_name_placeholder" to "örn. Dolar, Bitcoin",
        "currency_note_label" to "Notlar (İsteğe Bağlı)",
        "currency_note_placeholder" to "örn. Yerel özel kur notları",
        "currency_rate_error" to "Döviz değeri geçerli bir pozitif sayı olmalıdır.",
        "calc_with_app_title" to "%s Hesaplayıcı",
        "use_value_btn" to "Tutarı Kullan",
        "math_error" to "Matematik Hatası",

        "curr_USD" to "Amerikan Doları",
        "curr_TOMAN" to "İran Tümeni",
        "curr_RIAL" to "İran Riyali",
        "curr_EUR" to "Avro / Euro",
        "curr_GBP" to "İngiliz Sterlini",
        "curr_AFN" to "Afganistan Afganisi",
        "curr_BTC" to "Bitcoin",
        "curr_TON" to "Toncoin",
        "curr_ETH" to "Ethereum",
        "curr_SOL" to "Solana",
        "curr_BNB" to "Binance Coin",
        "curr_ADA" to "Cardano",
        "curr_DOGE" to "Dogecoin",
        "curr_XRP" to "Ripple",
        "curr_USDT" to "Tether USD",
        "curr_USDC" to "USD Coin",
        "curr_LTC" to "Litecoin",
        "curr_LINK" to "Chainlink",
        "curr_DOT" to "Polkadot",
        "curr_POL" to "Polygon",
        "curr_SHIB" to "Shiba Inu",
        "curr_AVAX" to "Avalanche",
        "curr_JPY" to "Japon Yeni",
        "curr_CAD" to "Kanada Doları",
        "curr_CHF" to "İsviçre Frangı",
        "curr_CNY" to "Çin Yuanı",
        "curr_TRY" to "Türk Lirası",
        "curr_AED" to "BAE Dirhemi",
        "curr_AUD" to "Avustralya Doları",
        "curr_TJS" to "Tacikistan Somonisi",
        "curr_SAR" to "Suudi Arabistan Riyali",
        "curr_KWD" to "Kuveyt Dinarı",
        "curr_QAR" to "Katar Riyali",
        "curr_OMR" to "Umman Riyali",
        "curr_BHD" to "Bahreyn Dinarı",
        "curr_IQD" to "Irak Dinarı",
        "curr_SYP" to "Suriye Lirası",
        "curr_LBP" to "Lübnan Lirası",
        "curr_JOD" to "Ürdün Dinarı",
        "curr_EGP" to "Mısır Lirası",
        "curr_YER" to "Yemen Riyali",
        "curr_KZT" to "Kazakistan Tengesi",
        "curr_UZS" to "Özbekistan Somu",
        "curr_AZN" to "Azerbaycan Manatı",
        "curr_AMD" to "Ermeni Dramı",
        "curr_GEL" to "Gürcistan Lari",
        "curr_ILS" to "İsrail Şekeli",
        "curr_DZD" to "Cezayir Dinarı",
        "curr_MAD" to "Fas Dirhemi",
        "curr_LYD" to "Libya Dinarı",
        "curr_TND" to "Tunus Dinarı",
        "curr_SDG" to "Sudan Lirası",
        "curr_INR" to "Hindistan Rupisi",
        "curr_RUB" to "Rus Rublesi",
        "curr_PKR" to "Pakistan Rupisi",
        "curr_BRL" to "Brezilya Reali",
        "curr_ZAR" to "Güney Afrika Randı",
        "curr_SGD" to "Singapur Doları",
        "curr_NZD" to "Yeni Zelanda Doları",
        "curr_KRW" to "Güney Kore Wonu",
        "curr_MXN" to "Meksika Pesosu",
        "curr_GOLD" to "Altın Ons Spot",
        "curr_GOLD_24K" to "24 Ayar Altın (Gram)",
        "curr_GOLD_18K" to "18 Ayar Altın (Gram)",
        "curr_SILVER" to "Gümüş Ons Spot",
        "curr_DIAMOND" to "Elmas (Karat)",
        "curr_PLATINUM" to "Platin Ons ",

        "tab_online" to "Çevrimiçi Mod",
        "creator_label" to "Geliştirici",
        "support_dev_title" to "💝 Geliştiriciyi Destekle",
        "support_dev_desc" to "Bu uygulamayı kullanmaktan keyif alıyorsanız ve gelişimini desteklemek isterseniz, aşağıdaki cüzdan adresini kullanarak isteğe bağlı bir katkıda bulunabilirsiniz. Desteğiniz uygulamanın geliştirilmesine ve sürdürülmesine yardımcı olur. İlginiz ve desteğiniz için teşekkür ederiz ❤️",
        "wallet_copied_msg" to "Cüzdan adresi kopyalandı!",
        "support_dev_warning" to "⚠️ Lütfen bu cüzdan adresine yalnızca USDT (BEP20) gönderin. Diğer varlıkların veya ağların gönderilmesi fonların kalıcı olarak kaybolmasına neden olabilir.",
        "secret_panel_title" to "Gizli Ayarlar Paneli",
        "secret_panel_desc" to "Gizli ayarlar panelinin kilidini açtınız. Aşağıdan gizli şifrenizi değiştirebilirsiniz.",
        "change_pass_title" to "Gizli Şifreyi Değiştir",
        "new_pass_placeholder" to "Yeni şifre...",
        "change_app_name_title" to "Uygulama Adını Değiştir",
        "new_app_name_placeholder" to "Yeni uygulama adı...",
        "change_app_icon_title" to "Uygulama Simge Stilini Değiştir",
        "picked_img_preview" to "Seçilen Resim Önizlemesi",
        "save_apply_log" to "Kaydet ve Uygula",
        "support_wallet_settings" to "Destek Cüzdan Ayarları",
        "enable_support_section" to "Destek Bölümünü Etkinleştir",
        "change_wallet_address" to "Cüzdan Adresini Değiştir",
        "new_wallet_placeholder" to "Yeni cüzdan adresi...",
        "change_wallet_qr" to "Cüzdan QR Kodunu Değiştir",
        "pick_from_gallery" to "Galeriden Seç",
        "reset_image" to "Görseli Sıfırla",
        "custom_text_above_wallet" to "Cüzdan Üstü Özel Metin",
        "custom_text_above_placeholder" to "Örn: Lütfen geliştiriciyi destekleyin...",
        "custom_text_below_wallet" to "Cüzdan Altı Özel Metin",
        "custom_text_below_placeholder" to "Örn: Sadece BEP20 USDT desteklenir...",
        "reset" to "Sıfırla",
        "secret_pass_title" to "Gizli Bölüm Şifresi",
        "secret_pass_desc" to "Bu bölümün kilidini açmak için lütfen gizli şifreyi girin:",
        "incorrect_pass" to "Hatalı Şifre!",
        "verify" to "Doğrula",

        "online_mode_title" to "Çevrimiçi Mod",
        "online_features_future" to "Çevrimiçi özellikler gelecek güncellemelerde eklenecektir.",
        "online_features_desc" to "Gelecek yükseltmeler bu modüle gerçek zamanlı banka kurları, küresel piyasa grafikleri ve otomatik API senkronizasyonu getirecektir."
    )

    private val frStrings = mapOf(
        "tab_offline" to "Convertisseur Hors-ligne",
        "tab_favorites" to "Favoris",
        "tab_history" to "Historique",
        "tab_settings" to "Paramètres",
        "settings_header" to "Paramètres de l'application",
        "settings_desc" to "Configurer les métriques d'affichage, les thèmes, les langues et les options système.",
        "currency_display_title" to "Mode de Calcul",
        "currency_display_desc" to "Définir si les valeurs sont affichées en Toman ou en Rial (1 Toman = 10 Rials).",
        "toman_label" to "Système Toman (Par défaut)",
        "rial_label" to "Système Rial (Facteur 10)",
        "theme_title" to "Thème de l'interface",
        "theme_system" to "Défaut Système",
        "theme_light" to "Thème Clair",
        "theme_dark" to "Thème Sombre Premium",
        "lang_title" to "Paramètres de Langue / Language",
        "lang_desc" to "Changer la langue d'affichage de l'application.",
        "lang_fa" to "فارسی (Persan)",
        "lang_en" to "English (Anglais)",
        "lang_ar" to "العربية (Arabe)",
        "lang_zh" to "中文 (Chinois)",
        "lang_de" to "Deutsch (Allemand)",
        "lang_tr" to "Türkçe (Turc)",
        "lang_fr" to "Français (French)",
        "about_title" to "À propos du Développeur",
        "about_name_label" to "Nom de l'application :",
        "about_version_label" to "Version :",
        "about_engine_label" to "Moteur Local :",
        "about_links_header" to "Support & Contact :",
        "about_telegram" to "Mon Canal Telegram (@digit_bazar)",
        "about_website" to "Mon Site Web",
        "search_hint" to "Rechercher une devise...",
        "add_currency" to "Ajouter une Devise",
        "edit_currency" to "Modifier la Devise",
        "save" to "Sauvegarder",
        "cancel" to "Annuler",
        "sync_title" to "Synchroniser & Restaurer",
        "sync_desc" to "Si les devises par défaut sont manquantes, cliquez ci-dessous pour forcer la restauration.",
        "sync_btn" to "Restaurer les devises système",
        "sync_success" to "Synchronisation réussie !",

        "app_desc_headline" to "Convertisseur multi-devises instantané. Appuyez sur un bloc pour choisir la devise de base.",
        "input_placeholder" to "Entrez le montant à convertir...",
        "input_label" to "Montant de base",
        "sort_by" to "Trier par :",
        "category_label" to "Catégorie :",
        "no_match_text" to "Aucune devise correspondante trouvée",
        "pinned_favorites" to "FAVORIS ÉPINGLÉS",
        "done" to "Terminé",
        "edit" to "Modifier",
        "fiat_header" to "DEVISES FIDUCIAIRES 💵",
        "digital_header" to "DEVISES NUMÉRIQUES 🪙",
        "commodity_header" to "MATIÈRES PREMIÈRES & MÉTAUX PRÉCIEUX ⚜️",
        "fiat_arrow" to "Fiat 💵 ➔",
        "crypto_arrow" to "Crypto 🪙 ➔",
        "gold_arrow" to "Or/Matières ⚜️ ➔",
        "favorites_empty_title" to "Aucun favori enregistré",
        "favorites_empty_desc" to "Allez dans l'onglet 'Convertisseur' et appuyez sur l'icône étoile pour l'épingler ici.",
        "history_empty_title" to "Historique des conversions vide",
        "history_empty_desc" to "Effectuez des calculs hors-ligne dans le convertisseur pour générer automatiquement l'historique.",
        "from_label" to "De",
        "to_label" to "À",
        "clear_btn" to "Effacer",
        "online_mode_title" to "Mode En Ligne",
        "online_mode_desc" to "Les fonctionnalités en ligne seront ajoutées dans les futures mises à jour.",
        "online_mode_subdesc" to "Les futures mises à jour apporteront les taux en direct des banques centrales, des graphiques mondiaux et une synchronisation API automatique.",
        "delete_currency" to "Supprimer",
        "currency_name_placeholder" to "ex. Dollar, Bitcoin",
        "currency_note_label" to "Notes (Optionnel)",
        "currency_note_placeholder" to "ex. Notes de taux de douane locaux",
        "currency_rate_error" to "La valeur d'échange doit être un nombre positif valide.",
        "calc_with_app_title" to "Calculatrice %s",
        "use_value_btn" to "Utiliser la valeur",
        "math_error" to "Erreur mathématique",

        "curr_USD" to "Dollar américain",
        "curr_TOMAN" to "Toman iranien",
        "curr_RIAL" to "Rial iranien",
        "curr_EUR" to "Euro",
        "curr_GBP" to "Livre sterling",
        "curr_AFN" to "Afghani afghan",
        "curr_BTC" to "Bitcoin",
        "curr_TON" to "Toncoin",
        "curr_ETH" to "Ethereum",
        "curr_SOL" to "Solana",
        "curr_BNB" to "Binance Coin",
        "curr_ADA" to "Cardano",
        "curr_DOGE" to "Dogecoin",
        "curr_XRP" to "Ripple",
        "curr_USDT" to "Tether USD",
        "curr_USDC" to "USD Coin",
        "curr_LTC" to "Litecoin",
        "curr_LINK" to "Chainlink",
        "curr_DOT" to "Polkadot",
        "curr_POL" to "Polygon",
        "curr_SHIB" to "Shiba Inu",
        "curr_AVAX" to "Avalanche",
        "curr_JPY" to "Yen japonais",
        "curr_CAD" to "Dollar canadien",
        "curr_CHF" to "Franc suisse",
        "curr_CNY" to "Yuan chinois",
        "curr_TRY" to "Livre turque",
        "curr_AED" to "Dirham des Émirats",
        "curr_AUD" to "Dollar australien",
        "curr_TJS" to "Somoni tadjik",
        "curr_SAR" to "Riyal saoudien",
        "curr_KWD" to "Dinar koweïtien",
        "curr_QAR" to "Riyal qatari",
        "curr_OMR" to "Riyal omanais",
        "curr_BHD" to "Dinar bahreïni",
        "curr_IQD" to "Dinar irakien",
        "curr_SYP" to "Livre syrienne",
        "curr_LBP" to "Livre libanaise",
        "curr_JOD" to "Dinar jordanien",
        "curr_EGP" to "Livre égyptienne",
        "curr_YER" to "Riyal yéménite",
        "curr_KZT" to "Tenge kazakh",
        "curr_UZS" to "Sum ouzbek",
        "curr_AZN" to "Manat azerbaïdjanais",
        "curr_AMD" to "Dram arménien",
        "curr_GEL" to "Lari géorgien",
        "curr_ILS" to "Shekel israélien",
        "curr_DZD" to "Dinar algérien",
        "curr_MAD" to "Dirham marocain",
        "curr_LYD" to "Dinar libyen",
        "curr_TND" to "Dinar tunisien",
        "curr_SDG" to "Livre soudanaise",
        "curr_INR" to "Roupie indienne",
        "curr_RUB" to "Rouble russe",
        "curr_PKR" to "Roupie pakistanaise",
        "curr_BRL" to "Réal brésilien",
        "curr_ZAR" to "Rand sud-africain",
        "curr_SGD" to "Dollar de Singapour",
        "curr_NZD" to "Dollar néo-zélandais",
        "curr_KRW" to "Won sud-coréen",
        "curr_MXN" to "Peso mexicain",
        "curr_GOLD" to "Once d'or",
        "curr_GOLD_24K" to "Or 24 carats (Gramme)",
        "curr_GOLD_18K" to "Or 18 carats (Gramme)",
        "curr_SILVER" to "Once d'argent",
        "curr_DIAMOND" to "Diamant (Carat)",
        "curr_PLATINUM" to "Once de platine",

        "tab_online" to "Mode en ligne",
        "creator_label" to "Créateur",
        "support_dev_title" to "💝 Soutenir le développeur",
        "support_dev_desc" to "Si vous appréciez cette application et souhaitez soutenir son développement, vous pouvez faire une contribution facultative en utilisant l'adresse de portefeuille ci-dessous. Votre soutien aide à améliorer et à maintenir l'application. Merci pour votre gentillesse et votre soutien ❤️",
        "wallet_copied_msg" to "Adresse du portefeuille copiée !",
        "support_dev_warning" to "⚠️ Veuillez envoyer uniquement de l'USDT (BEP20) à cette adresse de portefeuille. L'envoi d'autres actifs ou via d'autres réseaux peut entraîner une perte définitive des fonds.",
        "secret_panel_title" to "Panneau des paramètres secrets",
        "secret_panel_desc" to "Vous avez déverrouillé le panneau des paramètres secrets. Vous pouvez modifier votre mot de passe secret ci-dessous.",
        "change_pass_title" to "Modifier le mot de passe secret",
        "new_pass_placeholder" to "Nouveau mot de passe...",
        "change_app_name_title" to "Modifier le nom de l'application",
        "new_app_name_placeholder" to "Nouveau nom d'application...",
        "change_app_icon_title" to "Modifier le style d'icône d'application",
        "picked_img_preview" to "Aperçu de la photo sélectionnée",
        "save_apply_log" to "Enregistrer et appliquer",
        "support_wallet_settings" to "Paramètres de portefeuille de soutien",
        "enable_support_section" to "Activer la section de soutien",
        "change_wallet_address" to "Modifier l'adresse du portefeuille",
        "new_wallet_placeholder" to "Nouvelle adresse de portefeuille...",
        "change_wallet_qr" to "Modifier le code QR du portefeuille",
        "pick_from_gallery" to "Sélectionner depuis la galerie",
        "reset_image" to "Réinitialiser",
        "custom_text_above_wallet" to "Texte personnalisé au-dessus du portefeuille",
        "custom_text_above_placeholder" to "Ex: Merci de soutenir le développement...",
        "custom_text_below_wallet" to "Texte personnalisé au-dessous du portefeuille",
        "custom_text_below_placeholder" to "Ex: Uniquement BEP20 USDT pris en charge...",
        "reset" to "Réinitialiser",
        "secret_pass_title" to "Mot de passe de la section secrète",
        "secret_pass_desc" to "Veuillez saisir le mot de passe secret pour déverrouiller cette section :",
        "incorrect_pass" to "Mot de passe incorrect !",
        "verify" to "Vérifier",

        "online_mode_title" to "Mode en ligne",
        "online_features_future" to "Les fonctionnalités en ligne seront ajoutées dans les futures mises à jour.",
        "online_features_desc" to "Les futures mises à jour apporteront à ce module des taux bancaires en temps réel, des graphiques du marché mondial et une synchronisation API automatisée."
    )

    private val ruStrings = mapOf(
        "tab_offline" to "Офлайн Конвертер",
        "tab_favorites" to "Избранное",
        "tab_history" to "История",
        "tab_settings" to "Настройки",
        
        "settings_header" to "Настройки приложения",
        "settings_desc" to "Настройка метрик отображения, тем интерфейса, локализации и дополнительных параметров системы.",
        
        "currency_display_title" to "Режим отображения валют",
        "currency_display_desc" to "Определить модель расчёта в туманах или риалах (1 туман = 10 риалов).",
        "toman_label" to "Система Туман (по умолчанию)",
        "rial_label" to "Система Риал (коэффициент 10)",
        
        "theme_title" to "Тема оформления",
        "theme_system" to "Системная по умолчанию",
        "theme_light" to "Светлая эстетика",
        "theme_dark" to "Люксовый тёмный режим",
        
        "lang_title" to "Язык интерфейса / Language settings",
        "lang_desc" to "Изменить язык интерфейса приложения.",
        "lang_fa" to "فارسی (Persian)",
        "lang_en" to "English (US)",
        
        "app_name_custom_title" to "Изменить название приложения",
        "app_name_custom_desc" to "Введите желаемое название для отображения в приложении:",
        "app_name_placeholder" to "Новое название...",
        
        "app_icon_custom_title" to "Изменение логотипа/иконки",
        "app_icon_custom_desc" to "Выберите стиль логотипа или загрузите собственное изображение из галереи:",
        "app_icon_modern" to "Современный сияющий (Modern)",
        "app_icon_gold" to "Королевское золото (Royal Gold)",
        "app_icon_neon" to "Цифровой неон (Digital Neon)",
        "app_icon_vintage" to "Классический винтаж (Vintage Classic)",
        "app_icon_custom" to "Загруженное изображение из галереи",
        "app_icon_gallery_btn" to "Выбрать изображение из галереи устройства",
        
        "about_title" to "О разработчике и платформе",
        "about_name_label" to "Название приложения:",
        "about_version_label" to "Версия приложения:",
        "about_engine_label" to "Офлайн-движок:",
        "about_links_header" to "Связь с разработчиком:",
        "about_telegram" to "Мой Telegram-канал (@digit_bazar)",
        "about_website" to "Мой личный сайт",
        "about_creator" to "Создатель: Mr.Maxii",
        "created_by" to "Дизайн и разработка: Mr.Maxii",
        
        "search_hint" to "Поиск валюты по коду, знаку или названию...",
        "add_currency" to "Добавить свою валюту",
        "edit_currency" to "Редактировать валюту",
        "code_label" to "Код валюты (например, CAD)",
        "name_label" to "Полное имя (например, Канадский доллар)",
        "symbol_label" to "Символ валюты (например, C$)",
        "rate_label" to "Курс относительно 1 USD",
        "save" to "Сохранить изменения",
        "cancel" to "Отмена",
        "error_invalid" to "Пожалуйста, введите корректные параметры",
        
        "calc_title" to "Встроенный калькулятор",
        "calc_desc" to "Рассчитайте математическое выражение и вставьте результат прямо в поле ввода суммы конвертации.",
        "calc_hint" to "Пример: 1500 * (1.10 - 0.05) + 350",
        "calc_btn" to "Вставить результат в сумму конвертации",
        "calc_error" to "Неверная формула математического выражения",
        
        "fav_header" to "Ваше Избранное",
        "fav_desc" to "Список валют, закрепленных для быстрого доступа. Включите режим сортировки для изменения приоритета.",
        "fav_reorder_btn" to "Изменить порядок отображения",
        "fav_reorder_done" to "Завершить сортировку",
        
        "hist_header" to "История Конвертаций",
        "hist_desc" to "Журнал аудита всех проведённых офлайн калькуляций валют для последующего ознакомления.",
        "hist_clear_btn" to "Стереть всю историю конвертаций",
        "hist_empty" to "История конвертаций в системе пока пуста",
        
        "calculator_short" to "Калькулятор",
        
        "sort_fav_first" to "Сначала избранные",
        "sort_high_val" to "Максимальное значение",
        "sort_low_val" to "Минимальное значение",
        "sort_alpha_az" to "Алфавитный (А-Я)",
        "sort_alpha_za" to "Алфавитный (Я-А)",
        
        "sync_title" to "Синхронизация валют",
        "sync_desc" to "Если стандартные валюты (золото, серебро, афгани, TON и др.) были удалены или отсутствуют, нажмите кнопку ниже для полного восстановления списка по умолчанию.",
        "sync_btn" to "Сбросить и восстановить валюты системы",
        "sync_success" to "Синхронизация прошла успешно! Все валюты по умолчанию добавлены в базу данных.",
        "sync_confirm_title" to "Подтверждение синхронизации",
        "sync_confirm_msg" to "Вы уверены, что хотите сбросить и восстановить список валют по умолчанию?",
        "yes" to "Да",
        "no" to "Нет",
        
        "cat_all" to "Все активы 💫",
        "cat_fiat" to "Фиатные деньги 💵",
        "cat_crypto" to "Криптовалюты 🪙",
        "cat_commodity" to "Золото и сырье ⚜️",
        
        "app_desc_headline" to "Конвертер валют в реальном времени. Нажмите на блок валюты, чтобы сделать её базовой.",
        "input_placeholder" to "Введите сумму конвертации...",
        "input_label" to "Базовая сумма",
        "sort_by" to "Сортировка:",
        "category_label" to "Категория:",
        "no_match_text" to "Валюта не найдена",
        "pinned_favorites" to "ЗАКРЕПЛЕННЫЕ В ИЗБРАННОМ",
        "done" to "Готово",
        "edit" to "Изм.",
        "fiat_header" to "ФИАТНЫЕ ВАЛЮТЫ 💵",
        "digital_header" to "ЦИФРОВЫЕ ВАЛЮТЫ 🪙",
        "commodity_header" to "ДРАГМЕТАЛЛЫ И ТОВАРЫ ⚜️",
        "fiat_arrow" to "Фиат 💵 ➔",
        "crypto_arrow" to "Крипта 🪙 ➔",
        "gold_arrow" to "Золото ⚜️ ➔",
        "favorites_empty_title" to "Избранное пусто",
        "favorites_empty_desc" to "Перейдите во вкладку 'Конвертер' и нажмите на иконку звёздочки, чтобы закрепить валюту здесь.",
        "history_empty_title" to "Журнал истории пуст",
        "history_empty_desc" to "Производите расчёты в конвертере, чтобы журнал автоматически пополнялся записями.",
        "from_label" to "От",
        "to_label" to "До",
        "clear_btn" to "Очистить",
        "online_mode_title" to "Онлайн режим",
        "online_mode_desc" to "Онлайн-функции будут доступны в следующих обновлениях.",
        "online_mode_subdesc" to "В следующих версиях появятся курсы ЦБ в реальном времени, глобальные графики рынков и автосинхронизация по API.",
        "delete_currency" to "Удалить валюту",
        "currency_name_placeholder" to "например, Доллар, Биткоин",
        "currency_note_label" to "Заметки (Опционально)",
        "currency_note_placeholder" to "например, Заметки о таможенном курсе",
        "currency_rate_error" to "Курс обмена должен быть положительным числом.",
        "calc_with_app_title" to "Калькулятор %s",
        "use_value_btn" to "Использовать значение",
        "math_error" to "Математическая ошибка",

        "curr_USD" to "Доллар США",
        "curr_TOMAN" to "Иранский туман",
        "curr_RIAL" to "Иранский риал",
        "curr_EUR" to "Евро",
        "curr_GBP" to "Фунт стерлингов",
        "curr_AFN" to "Афганский афгани",
        "curr_BTC" to "Биткоин",
        "curr_TON" to "Тонкоин",
        "curr_ETH" to "Эфириум",
        "curr_SOL" to "Солана",
        "curr_BNB" to "Биткоин Кэш / BNB",
        "curr_ADA" to "Кардано",
        "curr_DOGE" to "Догикоин",
        "curr_XRP" to "Рипл",
        "curr_USDT" to "Тезер USD",
        "curr_USDC" to "Монета USD",
        "curr_LTC" to "Лайткоин",
        "curr_LINK" to "Чейнлинк",
        "curr_DOT" to "Полкадот",
        "curr_POL" to "Полигон",
        "curr_SHIB" to "Шиба Ину",
        "curr_AVAX" to "Аваланч",
        "curr_JPY" to "Японская иена",
        "curr_CAD" to "Канадский доллар",
        "curr_CHF" to "Швейцарский франк",
        "curr_CNY" to "Китайский юань",
        "curr_TRY" to "Турецкая лира",
        "curr_AED" to "Дирхам ОАЭ",
        "curr_AUD" to "Австралийский доллар",
        "curr_TJS" to "Таджикский сомони",
        "curr_SAR" to "Саудовский риял",
        "curr_KWD" to "Кувейтский динар",
        "curr_QAR" to "Катарский риал",
        "curr_OMR" to "Оманский риал",
        "curr_BHD" to "Бахрейнский динар",
        "curr_IQD" to "Иракский динар",
        "curr_SYP" to "Сирийский фунт",
        "curr_LBP" to "Ливанский фунт",
        "curr_JOD" to "Иорданский динар",
        "curr_EGP" to "Египетский фунт",
        "curr_YER" to "Йеменский риал",
        "curr_KZT" to "Казахстанский тенге",
        "curr_UZS" to "Узбекский сум",
        "curr_AZN" to "Азербайджанский манат",
        "curr_AMD" to "Армянский драм",
        "curr_GEL" to "Грузинский лари",
        "curr_ILS" to "Израильский шекель",
        "curr_DZD" to "Алжирский динар",
        "curr_MAD" to "Марокканский дирхам",
        "curr_LYD" to "Ливийский динар",
        "curr_TND" to "Тунисский динар",
        "curr_SDG" to "Суданский фунт",
        "curr_INR" to "Индийская рупия",
        "curr_RUB" to "Российский рубль",
        "curr_PKR" to "Пакистанская рупия",
        "curr_BRL" to "Бразильский реал",
        "curr_ZAR" to "Южноафриканский рэнд",
        "curr_SGD" to "Сингапурский доллар",
        "curr_NZD" to "Новозеландский доллар",
        "curr_KRW" to "Южнокорейская вона",
        "curr_MXN" to "Мексиканское песо",
        "curr_GOLD" to "Золото за унцию",
        "curr_GOLD_24K" to "Золото 24K (Грамм)",
        "curr_GOLD_18K" to "Золото 18K (Грамм)",
        "curr_SILVER" to "Серебро за унцию",
        "curr_DIAMOND" to "Бриллиант (Карат)",
        "curr_PLATINUM" to "Платина за унцию",

        "tab_online" to "Онлайн обновление",
        "creator_label" to "Создатель",
        "support_dev_title" to "💝 Поддержать разработчика",
        "support_dev_desc" to "Если вам нравится это приложение и вы хотите поддержать его разработку, вы можете сделать добровольный перевод на указанный ниже адрес кошелька. Ваша поддержка помогает улучшать и поддерживать приложение. Спасибо за вашу доброту и поддержку! ❤️",
        "wallet_copied_msg" to "Адрес кошелька скопирован!",
        "support_dev_warning" to "⚠️ Пожалуйста, отправляйте только USDT (BEP20) на этот адрес кошелька. Отправка других активов или через другие сети может привести к безвозвратной потере средств.",
        "secret_panel_title" to "Панель секретных настроек",
        "secret_panel_desc" to "Вы успешно разблокировали скрытую панель настроек. Ниже вы можете изменить секретный пароль.",
        "change_pass_title" to "Изменение секретного пароля",
        "new_pass_placeholder" to "Новый пароль...",
        "change_app_name_title" to "Изменение названия приложения",
        "new_app_name_placeholder" to "Новое имя приложения...",
        "change_app_icon_title" to "Изменить стиль иконки приложения",
        "picked_img_preview" to "Предварительный просмотр выбранного изображения",
        "save_apply_log" to "Сохранить изменения",
        "support_wallet_settings" to "Настройки кошелька поддержки разработчика",
        "enable_support_section" to "Активировать раздел поддержки",
        "change_wallet_address" to "Изменение адреса кошелька",
        "new_wallet_placeholder" to "Новый адрес кошелька...",
        "change_wallet_qr" to "Изменить QR-код кошелька",
        "pick_from_gallery" to "Выбрать из галереи",
        "reset_image" to "Сбросить изображение",
        "custom_text_above_wallet" to "Текст над кошельком (настраиваемый)",
        "custom_text_above_placeholder" to "Например: Спасибо за поддержку проекта...",
        "custom_text_below_wallet" to "Текст под кошельком (настраиваемый)",
        "custom_text_below_placeholder" to "Например: Поддерживается только сеть BEP20...",
        "reset" to "Сброс",
        "secret_pass_title" to "Пароль для секретного раздела",
        "secret_pass_desc" to "Пожалуйста, введите секретный пароль для доступа к разделу:",
        "incorrect_pass" to "Неверный пароль!",
        "verify" to "Подтвердить",

        "online_mode_title" to "Онлайн обновление",
        "online_features_future" to "Онлайн-функции будут добавлены в будущих обновлениях.",
        "online_features_desc" to "Будущие обновления принесут в этот модуль курсы валют в реальном времени, графики мировых рынков и автоматическую синхронизацию API."
    )

    fun get(key: String, lang: String): String {
        val map = when(lang.lowercase().trim()) {
            "fa" -> faStrings
            "ar" -> arStrings
            "zh" -> zhStrings
            "de" -> deStrings
            "tr" -> trStrings
            "fr" -> frStrings
            "ru" -> ruStrings
            else -> enStrings
        }
        return map[key] ?: enStrings[key] ?: faStrings[key] ?: key
    }

    fun getCurrencyName(code: String, defaultName: String, lang: String): String {
        val key = "curr_${code.uppercase().trim()}"
        val localized = get(key, lang)
        return if (localized == key) defaultName else localized
    }
}
